## General endpoints
### Get Products
GET http://localhost:4004/products/Products

## Orders
### Create new order
POST http://localhost:4004/orders/createOrder
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8

{
  "ID": "0de044d7-fb16-45dc-a7cc-ffc87334ca9d",
  "status": "New"
}

### Get user orders
GET http://localhost:4004/orders/UserOrders(223e4567-e89b-12d3-a456-426655440000)
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8



## Authentication
### Login
POST http://localhost:4004/auth/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"admin123"
}

### Get logged in user
GET http://localhost:4004/auth/loggedInUser
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8



## USER

### Get user
GET http://localhost:4004/users/Users(0de044d7-fb16-45dc-a7cc-ffc87334ca9d)
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8


### Update user
PATCH http://localhost:4004/users/Users(0de044d7-fb16-45dc-a7cc-ffc87334ca9d)
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8

{
  "firstName": "Kamala",
  "lastName": "Harris",
  "password": "kamalaHarris",
  "email": "kamala@harris.com",
  "role": "user"
}



## ADMIN
### Admin add user
POST http://localhost:4004/users/Users
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8

{
  "firstName": "Kamala",
  "lastName": "Harris",
  "password": "kamalaHarris",
  "email": "kamala@harris.com"
}

### Create Product
POST http://localhost:4004/products/createProduct
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8

{
    "name": "Golden Tree",
    "price": 50,
    "category": "Chocolate"
}

### Get users
GET http://localhost:4004/users/Users
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8

### Get users
GET http://localhost:4004/orders/Orders
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNjJmNWRjLTkyZjgtNGJjNC04ZmU0LTBmN2U0MzQ2ODg1NyIsImZpcnN0TmFtZSI6IkFETUlOIiwibGFzdE5hbWUiOiJBRE1JTiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk5MDMwMH0.jbtLId_PtuWaKWYJaH1YQbhlNU5X1MoLiLrbIkeITM8






